### ISSUE TITLE
WebSocket connection isn't established yet

### ISSUE THREAD

**Issue by python-programmer** [channelcat/sanic#1028]
i run the websocket sample code and get below errors:

```
2017-11-21 19:39:08 - (sanic)[ERROR]: Traceback (most recent call last):
File "/Users/xxxx/Documents/Projects/sanic_env/lib/python3.6/site-packages/sanic/app.py", line 503, in handle_request
response = await response
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/coroutines.py", line 128, in throw
return self.gen.throw(type, value, traceback)
File "/Users/xxxx/Documents/Projects/sanic_env/lib/python3.6/site-packages/sanic/app.py", line 247, in websocket_handler
await fut
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/coroutines.py", line 125, in send
return self.gen.send(value)
File "/Users/xxxx/PycharmProjects/BBServer/main.py", line 120, in feed
await ws.send(data)
File "/Users/xxxx/Documents/Projects/sanic_env/lib/python3.6/site-packages/websockets/protocol.py", line 334, in send
yield from self.ensure_open()
File "/Users/xxxx/Documents/Projects/sanic_env/lib/python3.6/site-packages/websockets/protocol.py", line 484, in ensure_open
raise InvalidState("WebSocket connection isn't established yet")
websockets.exceptions.InvalidState: WebSocket connection isn't established yet
```
What did I do wrong?

**Comment by m43k** [comment]
Duplicate of issue #1009

**Comment by python-programmer** [comment]
thank you for reply
