### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by GuangTianLi** [channelcat/sanic#1041]
When I use https://github.com/channelcat/sanic/wiki/Examples#motor, It traceback this error.
```
[2017-12-01 11:22:28 +0800] [16395] [ERROR] Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sanic/server.py", line 340, in write_response
    self.log_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sanic/server.py", line 317, in log_response
    if self.request.ip:
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sanic/request.py", line 172, in ip
    self._get_address()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sanic/request.py", line 190, in _get_address
    self._ip, self._port = self._socket
ValueError: too many values to unpack (expected 2)
```

**Comment by GuangTianLi** [comment]
It seem like the uvloop get more info from transport extra.Maybe It better way to unpack the information.
```
    def _get_address(self):
        self._socket = (self.transport.get_extra_info('peername') or
                        (None, None))
        self._ip = self._socket[0]
        self._port = self._socket[1]
```

**Comment by GuangTianLi** [comment]
It seem like the uvloop get more info from transport extra.Maybe It better way to unpack the information.
```
    def _get_address(self):
        self._socket = (self.transport.get_extra_info('peername') or
                        (None, None))
        self._ip = self._socket[0]
        self._port = self._socket[1]
```

**Comment by jmoraleda** [comment]
I have observed this error message after a recent python update that did not involve updating sanic, so it is a dependency that has changed.

I remark that the server works as expected in spite of the error message in the log.

This error can easily be reproduced by passing `host="localhost"` to the run argument. 

As a work around, passing `host="0.0.0.0"` instead of `host="localhost"` gets rid of the error message.

**Comment by r0fls** [comment]
I can't actually reproduce this. @jmoraleda are you able to test using the master branch? The logic referenced in https://github.com/channelcat/sanic/issues/1041#issuecomment-348392607 has already been implemented, so I think this is probably just an issue with the latest release, but not the master branch.

**Comment by jmoraleda** [comment]
Thank you @r0fls. I have not tried the master branch. This code reproduces it on version 0.7.0 (the latest on pypi):
```
from sanic import Sanic
from sanic.response import json

app = Sanic()

@app.route("/")
async def test(request):
    return json({"hello": "world"})

if __name__ == "__main__":
    app.run(host="localhost", port=8010)
```

**Comment by smagafurov** [comment]
@r0fls: can you release minor version on pypi with this fix?

**Comment by seemethere** [comment]
I can get on that.

**Comment by metron8** [comment]
@r0fls: can you release minor version on pypi with this fix? we really need this )

**Comment by pyk** [comment]
@metron8 as mentioned in #1134 , for now you can use the following command to get the latest version of Sanic:

```
pip install git+https://github.com/channelcat/sanic.git@b671546
```

note that the it will still tagged as `sanic==0.0.7` if you run `pip freeze`, so it may ruined your deployment. You can replace manually your `requirements.txt` to use the git url instead.

**Comment by r0fls** [comment]
Let's give @seemethere a few more days, otherwise I'll look into making a release.

**Comment by DirkGuijt** [comment]
Are we past "a few more days" yet?  o:)

**Comment by shvechikov** [comment]
I have this issue with the most recent PyPI version (0.7.0).
