### ISSUE TITLE
Multiple workers: RuntimeError - Event loop stopped before Future completed

### ISSUE THREAD

**Issue by pyk** [channelcat/sanic#1085]
My Sanic server is using fire-and-forget approach like the following

```python
from sanic import Sanic
from sanic import response
import asyncio

api = Sanic(__name__)

@api.listener("before_server_start")
async def initialize_tasks_set(api, loop):
    api.tasks = set()

async def busy_work(second):
    await asyncio.sleep(second)
    print("busy_work is DONE")

@api.get("/fire")
async def fire(request):
    future = asyncio.ensure_future(busy_work(10))
    api.tasks.add(future)
    future.add_done_callback(api.tasks.remove)
    return response.json({"status": "ok"})


@api.listener("before_server_stop")
async def wait_pending_busy_work(api, loop):
    print("waiting busy work")
    if len(api.tasks) > 0:
        await asyncio.wait(api.tasks, loop=loop)
    print("all busy work is done")


if __name__ == "__main__":
    api.run(workers=1)
```

The idea is to wait all pending tasks to complete before the server is stop.

When using a single worker, it run as expected :

```
% python sleep_server.py 
[2018-01-12 03:53:09 +0700] [11522] [INFO] Goin' Fast @ http://127.0.0.1:8000
[2018-01-12 03:53:09 +0700] [11522] [INFO] Starting worker [11522]
[2018-01-12 03:53:13 +0700] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8000/fire  200 15
[2018-01-12 03:53:13 +0700] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8000/fire  200 15
[2018-01-12 03:53:13 +0700] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8000/fire  200 15
[2018-01-12 03:53:13 +0700] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8000/fire  200 15
[2018-01-12 03:53:13 +0700] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8000/fire  200 15
[2018-01-12 03:53:14 +0700] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8000/fire  200 15
^C[2018-01-12 03:53:15 +0700] [11522] [INFO] Stopping worker [11522]
waiting busy work
busy_work is DONE
busy_work is DONE
busy_work is DONE
busy_work is DONE
busy_work is DONE
busy_work is DONE
all busy work is done
[2018-01-12 03:53:24 +0700] [11522] [INFO] Server Stopped
```

When I set the `api.run(workers=2)`, it raise the `RuntimeError`:

```
% python sleep_server.py 
[2018-01-12 03:55:16 +0700] [11604] [INFO] Goin' Fast @ http://127.0.0.1:8000
[2018-01-12 03:55:16 +0700] [11605] [INFO] Starting worker [11605]
[2018-01-12 03:55:16 +0700] [11606] [INFO] Starting worker [11606]
[2018-01-12 03:55:20 +0700] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8000/fire  200 15
[2018-01-12 03:55:20 +0700] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8000/fire  200 15
[2018-01-12 03:55:21 +0700] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8000/fire  200 15
[2018-01-12 03:55:21 +0700] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8000/fire  200 15
[2018-01-12 03:55:21 +0700] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8000/fire  200 15
[2018-01-12 03:55:21 +0700] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8000/fire  200 15
^C[2018-01-12 03:55:26 +0700] [11605] [INFO] Stopping worker [11605]
[2018-01-12 03:55:26 +0700] [11606] [INFO] Stopping worker [11606]
[2018-01-12 03:55:26 +0700] [11604] [INFO] Received signal SIGINT. Shutting down.
waiting busy work
all busy work is done
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pyk/.virtualenvs/kumparan-tracker-api/local/lib/python3.6/site-packages/sanic/server.py", line 631, in serve
    loop.run_until_complete(asyncio.sleep(0.1))
  File "uvloop/loop.pyx", line 1362, in uvloop.loop.Loop.run_until_complete
RuntimeError: Event loop stopped before Future completed.
[2018-01-12 03:55:26 +0700] [11604] [INFO] Server Stopped
```

Currently, I use `gunicorn` to solve ths problem:

```
% gunicorn sleep_server:api --bind 0.0.0.0:8000 --worker-class=sanic.worker.GunicornWorker --workers=2
[2018-01-12 03:56:46 +0700] [11703] [INFO] Starting gunicorn 19.7.1
[2018-01-12 03:56:46 +0700] [11703] [INFO] Listening at: http://0.0.0.0:8000 (11703)
[2018-01-12 03:56:46 +0700] [11703] [INFO] Using worker: sanic.worker.GunicornWorker
[2018-01-12 03:56:46 +0700] [11706] [INFO] Booting worker with pid: 11706
[2018-01-12 03:56:47 +0700] [11707] [INFO] Booting worker with pid: 11707
[2018-01-12 03:56:50 +0700] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8000/fire  200 15
[2018-01-12 03:56:50 +0700] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8000/fire  200 15
[2018-01-12 03:56:50 +0700] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8000/fire  200 15
[2018-01-12 03:56:50 +0700] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8000/fire  200 15
[2018-01-12 03:56:51 +0700] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8000/fire  200 15
^C[2018-01-12 03:56:54 +0700] [11703] [INFO] Handling signal: int
[2018-01-12 03:56:54 +0700] [11706] [INFO] Stopping server: 11706, connections: 1
[2018-01-12 03:56:54 +0700] [11706] [INFO] Error while closing socket [Errno 9] Bad file descriptor
[2018-01-12 03:56:55 +0700] [11707] [INFO] Stopping server: 11707, connections: 0
[2018-01-12 03:56:55 +0700] [11707] [INFO] Error while closing socket [Errno 9] Bad file descriptor
waiting busy work
all busy work is done
[2018-01-12 03:56:55 +0700] [11707] [INFO] Worker exiting (pid: 11707)
waiting busy work
busy_work is DONE
busy_work is DONE
busy_work is DONE
busy_work is DONE
busy_work is DONE
all busy work is done
[2018-01-12 03:57:01 +0700] [11706] [INFO] Worker exiting (pid: 11706)
[2018-01-12 03:57:01 +0700] [11703] [INFO] Shutting down: Master

```

**Comment by yunstanford** [comment]
I guess you are using `ctrl+c` to terminate your program, if you just send `kill -2 parent_process_pid`, then should be good. In multiprocess mode, Sanic has registered both SIGINT and SIGTERM for parent process and worker process, which cause the issue.

I will push a small fix for this.

**Comment by yunstanford** [comment]
I guess you were terminating your program by `ctrl+c`, if you tried `kill -2 parent_process_pid`, then you are probably good. this's mainly because both main process and worker process has registered SIGINT, and reacted to it. Ideally, main process should handle the shutdown of worker processes. 

will push a fix.

**Comment by pyk** [comment]
@yunstanford yes, I use `ctrl+c`. Thanks for the fix, I hope it's merged soon :+1:
