### ISSUE TITLE
websocket handlers returning 404 (or other status codes)

### ISSUE THREAD

**Issue by abingham** [channelcat/sanic#1147]
I've got a websocket handler which, under certain circumstances, I'd like to return 404 to the user rather than set up the websocket. To do this I'm simply raising `sanic.exceptions.NotFound` from the handler. However when I actually exercise this code what I see is this:
```
Traceback (most recent call last):
  File "/Users/abingham/.virtualenvs/cyber-dojo/lib/python3.6/site-packages/websockets/handshake.py", line 85, in check_request
    assert get_header('Upgrade').lower() == 'websocket'
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/abingham/.virtualenvs/cyber-dojo/lib/python3.6/site-packages/sanic/websocket.py", line 63, in websocket_handshake
    key = handshake.check_request(get_header)
  File "/Users/abingham/.virtualenvs/cyber-dojo/lib/python3.6/site-packages/websockets/handshake.py", line 93, in check_request
    raise InvalidHandshake("Invalid request") from exc
websockets.exceptions.InvalidHandshake: Invalid request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/abingham/.virtualenvs/cyber-dojo/lib/python3.6/site-packages/sanic/app.py", line 556, in handle_request
    response = await response
  File "/Users/abingham/.virtualenvs/cyber-dojo/lib/python3.6/site-packages/sanic/app.py", line 259, in websocket_handler
    ws = await protocol.websocket_handshake(request, subprotocols)
  File "/Users/abingham/.virtualenvs/cyber-dojo/lib/python3.6/site-packages/sanic/websocket.py", line 66, in websocket_handshake
    raise InvalidUsage('Invalid websocket request')
sanic.exceptions.InvalidUsage: Invalid websocket request
```

That is, I get a 400 response from the `InvalidUsage` exception.

Am I just wrong in expecting to be able to return a 404? I'd be happy to be told that there's a (justifiable) reason not to be allowed to do this.

If it should be supported, am I doing something wrong here, or is this a bug in sanic/websockets/something?

**Comment by rafmagns-skepa-dreag** [comment]
Hi @abingham, it seems your initial issue is that you're missing the upgrade header or it's set incorrectly on the initial HTTP request. I've been dealing with the same issue. You'll need to solve this issue or catch the exception before you can even begin to deal with raising a `sanic.exceptions.NotFound ` from your websocket route.

I just did a test with a working implementation. Raising an exception from the websocket handler will not do what you want it to. The websocket request will do the websocket handshake which is implemented in websockets/sanic. This will return a 101 to the client. Afterward, if you raise `sanic.exceptions.NotFound` from your handler, all you will do is close the websocket connection and maybe write some output to your log file. 

You might be able to set up middleware that runs before the request is fully processed that can return a 404. If you `return` or `raise` from Sanic middleware, it will abort the rest of the request.

Hope this helps!
