### ISSUE TITLE
UnicodeEncodeError on server startup

### ISSUE THREAD

**Issue by antonagestam** [channelcat/sanic#1150]
Stumbled on a strange and kinda funny problem, it seems like sanic fails to print sanic on startup. It seems like the server is otherwise functioning healthy. This might very well be a problem with my environment and not with sanic per se.

```
$ python -m server.server
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 62-66: ordinal not in range(128)
Call stack:
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/antonagestam/python_projects/achtung/server/server.py", line 73, in <module>
    app.run(host="0.0.0.0", port=port, debug=True)
  File "/Users/antonagestam/python_projects/achtung/.venv/lib/python3.6/site-packages/sanic/app.py", line 641, in run
    access_log=access_log)
  File "/Users/antonagestam/python_projects/achtung/.venv/lib/python3.6/site-packages/sanic/app.py", line 803, in _helper
    logger.debug(self.config.LOGO)
Message: '\n                 \u2584\u2584\u2584\u2584\u2584\n        \u2580\u2580\u2580\u2588\u2588\u2588\u2588\u2588\u2588\u2584\u2584\u2584       _______________\n      \u2584\u2584\u2584\u2584\u2584  \u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2584  /                 \\\n     \u2580\u2580\u2580\u2580\u2588\u2588\u2588\u2588\u2588\u258c \u2580\u2590\u2584 \u2580\u2590\u2588 |   Gotta go fast!  |\n   \u2580\u2580\u2588\u2588\u2588\u2588\u2588\u2584\u2584 \u2580\u2588\u2588\u2588\u2588\u2588\u2588\u2584\u2588\u2588 | _________________/\n   \u2580\u2584\u2584\u2584\u2584\u2584  \u2580\u2580\u2588\u2584\u2580\u2588\u2550\u2550\u2550\u2550\u2588\u2580 |/\n        \u2580\u2580\u2580\u2584  \u2580\u2580\u2588\u2588\u2588 \u2580       \u2584\u2584\n     \u2584\u2588\u2588\u2588\u2580\u2580\u2588\u2588\u2584\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2584 \u2584\u2580\u2580\u2580\u2580\u2580\u2580\u2588\u258c\n   \u2588\u2588\u2580\u2584\u2584\u2584\u2588\u2588\u2580\u2584\u2588\u2588\u2588\u2580 \u2580\u2580\u2588\u2588\u2588\u2588      \u2584\u2588\u2588\n\u2584\u2580\u2580\u2580\u2584\u2588\u2588\u2584\u2580\u2580\u258c\u2588\u2588\u2588\u2588\u2592\u2592\u2592\u2592\u2592\u2592\u2588\u2588\u2588     \u258c\u2584\u2584\u2580\n\u258c    \u2590\u2580\u2588\u2588\u2588\u2588\u2590\u2588\u2588\u2588\u2592\u2592\u2592\u2592\u2592\u2590\u2588\u2588\u258c\n\u2580\u2584\u2584\u2584\u2584\u2580   \u2580\u2580\u2588\u2588\u2588\u2588\u2592\u2592\u2592\u2592\u2584\u2588\u2588\u2580\n          \u2580\u2580\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2580\n        \u2584\u2584\u2588\u2588\u2580\u2588\u2588\u2588\u2588\u2588\u2588\u2580\u2588\n      \u2584\u2588\u2588\u2580     \u2580\u2580\u2580  \u2588\n     \u2584\u2588             \u2590\u258c\n \u2584\u2584\u2584\u2584\u2588\u258c              \u2580\u2588\u2584\u2584\u2584\u2584\u2580\u2580\u2584\n\u258c     \u2590                \u2580\u2580\u2584\u2584\u2584\u2580\n \u2580\u2580\u2584\u2584\u2580\n'
Arguments: ()
[2018-03-03 14:10:43 +0100] [36439] [INFO] Goin' Fast @ http://0.0.0.0:8000
[2018-03-03 14:10:43 +0100] [36439] [INFO] Starting worker [36439]
```

```
$ pip freeze
aiofiles==0.3.2
aioredis==1.0.0
async-timeout==2.0.0
hiredis==0.2.0
httptools==0.0.10
sanic==0.7.0
ujson==1.35
uvloop==0.9.1
websockets==4.0.1
$ python --version
Python 3.6.1
$ uname -a
Darwin dev-antonagestam 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
```

(macos 10.13.3)

**Comment by antonagestam** [comment]
Nevermind, this was indeed a problem with my environment. Setting the bellow in my `.bash_profile` fixed the problem.

```sh
export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_ALL=
```

**Comment by adamgering** [comment]
This should return UTF-8:

python3 -c 'import sys; print(sys.stdout.encoding)'

**Comment by adamgering** [comment]
Fixed in docker via:

RUN apt-get install -y --allow-unauthenticated -q locales \
&& locale-gen en_US.UTF-8

ENV LC_ALL=en_US.UTF-8

**Comment by fallinloveq** [comment]
在windows环境下运行也会打印错误信息：
unicodeencodeerror: 'gbk' codec can't encode character '\u2580' in position 778: illegal multibyte sequenceCall stack:

**Comment by fallinloveq** [comment]
在windows环境下运行同时打印错误信息：
unicodeencodeerror: 'gbk' codec can't编码字符 '\u2580' inposition 778: invalid multibyteequenceCall stack:

windows 10 企业版
python 3.10.1
sanic 24.6.0

**Comment by fallinloveq** [comment]
在windows环境下运行服务也会报错：
错误打印信息： unicodeencodeerror: 'gbk' codec can't Encoding Char '\u2580' inposition 778: invalid multibyteequenceCall stack:

windows 10 企业版
python 3.10.1
sanic 24.6.0
