### ISSUE TITLE
Error related to class based views

### ISSUE THREAD

**Issue by levismiller** [channelcat/sanic#1208]
Using the following code sample from docs page but I get an error in the Router at startup. 

class SimpleView(HTTPMethodView):
  def get(self, request):
      return text('I am get method')
  def post(self, request):
      return text('I am post method')
  def put(self, request):
      return text('I am put method')
  def patch(self, request):
      return text('I am patch method')
  def delete(self, request):
      return text('I am delete method')

**app.add_route(SimpleView.as_view(), '/')**

Seeing the following error:

Traceback (most recent call last):
  File "/Users/lsm/UserAPI/env/lib/python3.6/site-packages/sanic/app.py", line 546, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/Users/lsm/UserAPI/env/lib/python3.6/site-packages/sanic/router.py", line 343, in get
    return self._get(request.path, request.method, '')
  File "/Users/lsm/UserAPI/env/lib/python3.6/site-packages/sanic/router.py", line 397, in _get
    route_handler = route.handler
AttributeError: 'Route' object has no attribute 'handler'

Noticed on line 257 in router.py in the call to Route() handler seems to be missing from the namedtuple above but I am new to the framework and don't fully understand what is going on so this may not be helpful.

        if route:
            route = merge_route(route, methods, handler)
        else:
            # route = Route(['view', 'methods', 'pattern', 'parameters', 'name', 'uri')
            route = Route(handler=handler, methods=methods, pattern=pattern,
                parameters=parameters, name=handler_name, uri=uri)

Route = namedtuple(
    'Route',
    ['view', 'methods', 'pattern', 'parameters', 'name', 'uri'])

Here is a pip freeze:
aiofiles==0.3.2
certifi==2018.4.16
chardet==3.0.4
httptools==0.0.11
idna==2.6
protobuf==3.5.2.post1
requests==2.18.4
sanic==0.7.0
six==1.11.0
ujson==1.35
urllib3==1.22
uvloop==0.9.1
websockets==4.0.1
wget==3.2

**Comment by levismiller** [comment]
Removed env and did a pip install -r requirements and it works now. Not sure what I was seeing there.
