### ISSUE TITLE
Running app with multiple workers raises Exception on port

### ISSUE THREAD

**Issue by iambrettstar** [channelcat/sanic#1289]
When running my app like so:
`app.run(host='0.0.0.0', port=5000, workers=4)`
I encounter the following exception:
```
Traceback (most recent call last):
  ...
  File "~/venv/lib64/python3.6/site-packages/sanic/app.py", line 661 in run
    serve_multiple(server_settings, workers)
  
  File "~/venv/lib64/python3.6/site-packages/sanic/server.py", line 668, in serve_multiple
    sock.bind((server_settings['host'], server_settings['port']))
TypeError: an integer is required (got type str)
```

`server_settings['port']` is a string, which obviously seems to break `sock.bind`.

When running with just 1 worker, it calls `loop.create_server(server, host, port.....` instead of `sock.bind` and appears to work fine.

**Comment by chris-aeviator** [comment]
I'm getting this with  workers=1 - how did you solve it?
