### ISSUE TITLE
Sanic Websockets over SSL aka WSS

### ISSUE THREAD

**Issue by Lagicrus** [channelcat/sanic#1293]
Does Sanic allow WebSocket connections over WSS?
I ask this as the code below that worked with just a ws protocol method worked fine
```
@app.websocket("/online")
async def online_handler(request, ws):
    while True:
        connection = await ws.recv()
        await ws.send("Online")
```
But upon using nginx to upgrade the request so it is served as a WSS it instead breaks and gives me 
```
web_1       | [2018-08-17 23:42:04 +0000] [1] [ERROR] Traceback (most recent call last):
web_1       |   File "/usr/local/lib/python3.7/site-packages/sanic/server.py", line 220, in data_received
web_1       |     self.parser.feed_data(data)
web_1       |   File "httptools/parser/parser.pyx", line 193, in httptools.parser.parser.HttpParser.feed_data
web_1       | httptools.parser.errors.HttpParserInvalidMethodError: invalid HTTP method
```
I am not sure if I need to look into fixing my nginx code or if the issue lies with Sanic.
Any help will be appreciated 

Edit
After changing my nginx config again into using a local http connection instead of a https connection
I now get this error on sanics side
```
web_1       | Traceback (most recent call last):
web_1       |   File "/usr/local/lib/python3.7/site-packages/sanic/app.py", line 556, in handle_request
web_1       |     response = await response
web_1       |   File "/usr/local/lib/python3.7/site-packages/sanic/app.py", line 259, in websocket_handler
web_1       |     ws = await protocol.websocket_handshake(request, subprotocols)
web_1       |   File "/usr/local/lib/python3.7/site-packages/sanic/websocket.py", line 66, in websocket_handshake
web_1       |     raise InvalidUsage('Invalid websocket request')
web_1       | sanic.exceptions.InvalidUsage: Invalid websocket request
```

**Comment by Lagicrus** [comment]
The issue is due to Squid (the proxy server)'s SSL interception, this, in turn, caused a bad request status 400. When I don't use the proxy it works fine.
