### ISSUE TITLE
Incompatible with windows

### ISSUE THREAD

**Issue by martmists** [channelcat/sanic#17]
```
C:\Users\martijn>pip install https://github.com/channelcat/sanic/archive/master.zip
Collecting https://github.com/channelcat/sanic/archive/master.zip
  Downloading https://github.com/channelcat/sanic/archive/master.zip
     | 30kB 364kB/s
Collecting uvloop>=0.5.3 (from Sanic==0.1.0)
  Downloading uvloop-0.5.4.tar.gz (1.9MB)
    100% |################################| 1.9MB 180kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\martijn\AppData\Local\Temp\pip-build-gylxe2o1\uvloop\setup.py", line 9, in <module>
        raise RuntimeError('uvloop does not support Windows at the moment')
    RuntimeError: uvloop does not support Windows at the moment

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\martijn\AppData\Local\Temp\pip-build-gylxe2o1\uvloop\
```

I know this is technically a uvloop issue, but since it affects this repo as well I suggest making an alternative for windows users

**Comment by guzgarcia** [comment]
Any updates about this issue?

**Comment by martmists** [comment]
it works on bash on ubuntu on windows 10, but native support would be easier

**Comment by guzgarcia** [comment]
Thanks for the info. Yeah, would be a lot easier. I've seen a issue talking about this on uvloop repo without important updates :(

**Comment by seemethere** [comment]
Until uvloop has windows support sanic will unfortunately not have windows support, will re-open if / when uvloop gets windows support
