### ISSUE TITLE
DOC blueprint listener error

### ISSUE THREAD

**Issue by longtian001** [channelcat/sanic#196]
bp = Blueprint('my_blueprint')

@bp.listener('before_server_start')
async def setup_connection():
    global database
    database =PostgresqlDatabase(database='webdb',host='127.0.0.1',user='postgres',password='111111')

@bp.listener('after_server_stop')
async def close_connection():
    await database.close()

Error Msg:

2016-12-14 14:25:09,151: INFO: Goin' Fast @ http://0.0.0.0:8000
2016-12-14 14:25:09,152: ERROR: Experienced exception while trying to serve
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/Sanic-0.1.8-py3.5.egg/sanic/sanic.py", line 304, in run
    serve(**server_settings)
  File "/usr/local/lib/python3.5/site-packages/Sanic-0.1.8-py3.5.egg/sanic/server.py", line 243, in serve
    trigger_events(before_start, loop)
  File "/usr/local/lib/python3.5/site-packages/Sanic-0.1.8-py3.5.egg/sanic/server.py", line 211, in trigger_events
    result = event(loop)
TypeError: setup_connection() takes 0 positional arguments but 2 were given
2016-12-14 14:25:09,156: INFO: Server Stopped
[root@localhost webapp]#

**Comment by wojunnihou** [comment]
async def setup_connection(sanic_app,loop):

**Comment by longtian001** [comment]
**Error: Address already in use**

1.main.py 
# more main.py 
from sanic import Sanic
from my_blueprint import bp
app = Sanic(__name__)
app.blueprint(bp)
app.run(host='0.0.0.0', port=8000, debug=True)

2.my_blueprint.py
# more my_blueprint.py 
from sanic import Blueprint
from sanic.response import json, text, html
## Jinja2 template ####
from jinja2 import Environment, PackageLoader
env = Environment(loader=PackageLoader('my_blueprint', 'templates'))
## database ####
import uvloop, peewee
from peewee_async import PostgresqlDatabase
bp = Blueprint('my_blueprint')
@bp.listener('before_server_start')
async def setup_connection(sanic_app,loop):
    global database
    database =PostgresqlDatabase(database='webdb',host='127.0.0.1',user='postgres',password='111111')

@bp.listener('after_server_stop')
async def close_connection():
    await database.close()

# router define
@bp.route('/')
async def bp_root(request):
    serialized_obj = []
    cursor = database.execute_sql('select * from t1;')
    for row in cursor.fetchall():
         serialized_obj.append({
            'id': row[0],
            'name': row[1]}
        )
    template = env.get_template('index.html')
    content=template.render(items=serialized_obj)
    return html(content)

# 

running 


# python main.py 
2016-12-14 16:02:53,187: DEBUG: 
                 ▄▄▄▄▄
        ▀▀▀██████▄▄▄       _______________
      ▄▄▄▄▄  █████████▄  /                 \
     ▀▀▀▀█████▌ ▀▐▄ ▀▐█ |   Gotta go fast!  |
   ▀▀█████▄▄ ▀██████▄██ | _________________/
   ▀▄▄▄▄▄  ▀▀█▄▀█════█▀ |/
        ▀▀▀▄  ▀▀███ ▀       ▄▄
     ▄███▀▀██▄████████▄ ▄▀▀▀▀▀▀█▌
   ██▀▄▄▄██▀▄███▀ ▀▀████      ▄██
▄▀▀▀▄██▄▀▀▌████▒▒▒▒▒▒███     ▌▄▄▀
▌    ▐▀████▐███▒▒▒▒▒▐██▌
▀▄▄▄▄▀   ▀▀████▒▒▒▒▄██▀
          ▀▀█████████▀
        ▄▄██▀██████▀█
      ▄██▀     ▀▀▀  █
     ▄█             ▐▌
 ▄▄▄▄█▌              ▀█▄▄▄▄▀▀▄
▌     ▐                ▀▀▄▄▄▀
 ▀▀▄▄▀

2016-12-14 16:02:53,191: INFO: Goin' Fast @ http://0.0.0.0:8000
2016-12-14 16:02:53,204: ERROR: Unable to start server
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 867, in uvloop.loop.Loop._create_server (uvloop/loop.c:19819)
  File "uvloop/handles/streamserver.pyx", line 43, in uvloop.loop.UVStreamServer.listen (uvloop/loop.c:76180)
  File "uvloop/handles/streamserver.pyx", line 80, in uvloop.loop.UVStreamServer._fatal_error (uvloop/loop.c:76691)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/Sanic-0.1.8-py3.5.egg/sanic/server.py", line 262, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1186, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25057)
  File "uvloop/future.pyx", line 146, in uvloop.loop.BaseFuture.result (uvloop/loop.c:108166)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:107674)
  File "uvloop/future.pyx", line 372, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:111405)
  File "uvloop/loop.pyx", line 1346, in create_server (uvloop/loop.c:26927)
  File "uvloop/loop.pyx", line 871, in uvloop.loop.Loop._create_server (uvloop/loop.c:19958)
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 8000): address already in use
2016-12-14 16:02:53,211: INFO: Server Stopped
#

**Comment by longtian001** [comment]
sorry, another terminal already running one. and that's OK
wojunnihou, thank you very much.
