### ISSUE TITLE
ImportError: cannot import name 'Sanic'

### ISSUE THREAD

**Issue by mobdim** [channelcat/sanic#272]
Hello all.
I'm newbie.
I installed this module.

`pip3.5 show sanic`
```
Name: Sanic
Version: 0.1.9
Summary: A microframework based on uvloop, httptools, and learnings of flask
Home-page: http://github.com/channelcat/sanic/
Author: Channel Cat
Author-email: channelcat@gmail.com
License: MIT
Location: /usr/local/lib/python3.5/site-packages
Requires: uvloop, httptools, ujson, aiofiles, multidict
```

example code: (sanic.py)
```
from sanic import Sanic
from sanic.response import json

app = Sanic(__name__)


@app.route("/")
async def test(request):
    return json({"test": True})


app.run(host="0.0.0.0", port=8000)
```

Start, I get the error:
`python3.5 sanic.py`

```
Traceback (most recent call last):
  File "sanic.py", line 1, in <module>
    from sanic import Sanic
  File "/var/www/html/sanic.py", line 1, in <module>
    from sanic import Sanic
ImportError: cannot import name 'Sanic'
```

What am I doing wrong?

P.S. Flask runs without errors.

**Comment by seemethere** [comment]
How did you go about installing Sanic?

**Comment by mobdim** [comment]
centos 6.8

just run
`pip3.5 install sanic`

**Comment by mobdim** [comment]
@yoloseem Thanks 😂

**Comment by Zenexya** [comment]
@yoloseem lol I literally had it called sanic.py
