### ISSUE TITLE
`Bad file descriptor` when running multiple workers with explicit loop under macos

### ISSUE THREAD

**Issue by gpip** [channelcat/sanic#305]
Hello,

When I run the following using either master's HEAD or the latest release:

```
import asyncio

import uvloop
from sanic import Sanic

asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
loop = asyncio.get_event_loop()

app = Sanic()
app.run(loop=loop, workers=2)
```

The following traceback is generated:

```
2017-01-17 03:17:51,090: INFO: Goin' Fast @ http://127.0.0.1:8000
2017-01-17 03:17:51,090: INFO: Spinning up 2 workers...
2017-01-17 03:17:51,096: ERROR: Unable to start server
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 568, in uvloop.loop.Loop._add_reader (uvloop/loop.c:14392)
KeyError: 16

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../lib/python3.6/site-packages/Sanic-0.2.0-py3.6.egg/sanic/server.py", line 303, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1198, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25480)
  File "uvloop/loop.pyx", line 1191, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25324)
  File "uvloop/loop.pyx", line 1100, in uvloop.loop.Loop.run_forever (uvloop/loop.c:24056)
  File "uvloop/loop.pyx", line 363, in uvloop.loop.Loop._run (uvloop/loop.c:11491)
  File "uvloop/loop.pyx", line 216, in uvloop.loop.Loop._setup_signals (uvloop/loop.c:9069)
  File "uvloop/loop.pyx", line 570, in uvloop.loop.Loop._add_reader (uvloop/loop.c:14440)
  File "uvloop/handles/poll.pyx", line 30, in uvloop.loop.UVPoll.new (uvloop/loop.c:61297)
  File "uvloop/handles/poll.pyx", line 18, in uvloop.loop.UVPoll._init (uvloop/loop.c:61184)
OSError: [Errno 9] Bad file descriptor
2017-01-17 03:17:51,097: ERROR: Unable to start server
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 568, in uvloop.loop.Loop._add_reader (uvloop/loop.c:14392)
KeyError: 17

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../lib/python3.6/site-packages/Sanic-0.2.0-py3.6.egg/sanic/server.py", line 303, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1198, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25480)
  File "uvloop/loop.pyx", line 1191, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25324)
  File "uvloop/loop.pyx", line 1100, in uvloop.loop.Loop.run_forever (uvloop/loop.c:24056)
  File "uvloop/loop.pyx", line 363, in uvloop.loop.Loop._run (uvloop/loop.c:11491)
  File "uvloop/loop.pyx", line 216, in uvloop.loop.Loop._setup_signals (uvloop/loop.c:9069)
  File "uvloop/loop.pyx", line 570, in uvloop.loop.Loop._add_reader (uvloop/loop.c:14440)
  File "uvloop/handles/poll.pyx", line 30, in uvloop.loop.UVPoll.new (uvloop/loop.c:61297)
  File "uvloop/handles/poll.pyx", line 18, in uvloop.loop.UVPoll._init (uvloop/loop.c:61184)
OSError: [Errno 9] Bad file descriptor
2017-01-17 03:17:51,100: INFO: Server Stopped
```

Considering that it's required to share the async loop between sanic and a async db (when using that), it seems there's no way to currently use sanic with multiple workers. Or maybe there's a different way to achieve that? (maybe use nginx in front of it and avoid using the `workers` option?)

**Comment by gpip** [comment]
As a work around I started using the `before_start` param in `app.run` to start the db connection from `asyncpgsa`.

**Comment by seemethere** [comment]
I noticed this earlier as well while debugging another issue. I will look into this later tonight.

**Comment by squeaky-pl** [comment]
I think this is related to asyncio design decision not to survive forking. Sanic does forking of workers using multiprocessing. In your case you created a loop before forking already in the master process and then you are forking in `app.run` with two workers which will create their own loops (which is forbidden in asyncio) that leads to undefined results. You could overcome this using fork+exec or initializing the loop after forking. But that would mean you would need to write your own version of `app.run`. 

See https://bugs.python.org/issue21998 for related discussion

**Comment by seemethere** [comment]
Yeah it's probably time to talk about not being able to pass a loop into the application especially if it's going to create problems like this and if asyncio doesn't support it themselves.

**Comment by squeaky-pl** [comment]
You could still allow that with 1 worker (forking not involved in this scenario) but maybe print warning to stderr and explode with exception if there was already loop initialized in parent process before forking. Maybe actually not worth it.

**Comment by r0fls** [comment]
Passing the loop is causing issues with the single worker implementation as well:
https://github.com/channelcat/sanic/issues/329

**Comment by seemethere** [comment]
Forking an event loop is not supported by base asyncio. This is an upstream asyncio bug. Closing, will reopen if necessary.
