### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by skytoup** [channelcat/sanic#485]
when upgrade to 0.3.1

I'm using a Blueprint
```
bp = Blueprint('test', 'test')

class TestView(HTTPMethodView):
    def get(self, request, msg):
        return text('hello world')

bp.add_route(TestView.as_view(), '/<msg:string>')

app.blueprint(bp)
```
Got the exception:
```
2017-02-24 15:10:51,494: ERROR: Traceback (most recent call last):
  File "/Users/apple/Documents/PythonProject/pyenv/AppServer/lib/python3.5/site-packages/sanic/sanic.py", line 320, in handle_request
    handler, args, kwargs = self.router.get(request)
  File "/Users/apple/Documents/PythonProject/pyenv/AppServer/lib/python3.5/site-packages/sanic/router.py", line 266, in get
    return self._get(request.url, request.method, '')
  File "/Users/apple/Documents/PythonProject/pyenv/AppServer/lib/python3.5/site-packages/sanic/router.py", line 297, in _get
    if match and method in route.methods:
TypeError: argument of type 'NoneType' is not iterable
```

if i set methods in add_route, it can work
```
bp.add_route(TestView.as_view(), '/<msg:string>', ['GET'])
```

**Comment by r0fls** [comment]
I can't reproduce this. I'm using the below:

```python
from sanic.app import Sanic
from sanic.response import text
from sanic.blueprints import Blueprint
from sanic.views import HTTPMethodView

app = Sanic()

bp = Blueprint('test', 'test')

class TestView(HTTPMethodView):
    def get(self, request, msg):
        return text('hello world')

bp.add_route(TestView.as_view(), '/<msg:string>')

app.blueprint(bp)
app.run(debug=True)
```

Do I need to curl the app to get the exception? If so, what url are you suing to make the request?

**Comment by skytoup** [comment]
```
from sanic import Blueprint, Sanic
from sanic.views import HTTPMethodView
from sanic.response import text

app = Sanic(__name__)

bp = Blueprint('test', 'test')


class TestView(HTTPMethodView):
    def get(self, request, msg):
        return text('hello world: {}'.format(msg))


bp.add_route(TestView.as_view(), '/<msg:string>')

app.blueprint(bp)

app.run(debug=True)
```

curl http://127.0.0.1:8000/test/123 -v

Thank

**Comment by r0fls** [comment]
Hmm, I still can't reproduce I get `hello world: 123` and no error logged. It does say I'm using sanic version 0.3.1, but I may have included some newer commits. Can you manually install from the master branch, by doing a `git clone` of the repo and `python3 setup.py install`?

**Comment by skytoup** [comment]
After clone master and install.
It's really no problem!!!
Thank~
