### ISSUE TITLE
Cant install 0.4.0 release

### ISSUE THREAD

**Issue by gerasim13** [channelcat/sanic#492]
Hello, i cant install latest release.
Here is part of log from gitlab-ci:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python3.5/site-packages/pip/commands/install.py", line 310, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3.5/site-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3.5/site-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3.5/site-packages/pip/req/req_set.py", line 647, in _prepare_file
    set(req_to_install.extras) - set(dist.extras)
  File "/usr/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2810, in extras
    return [dep for dep in self._dep_map if dep]
  File "/usr/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2624, in _dep_map
    dm.setdefault(extra,[]).extend(parse_requirements(reqs))
  File "/usr/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2980, in parse_requirements
    "version spec")
  File "/usr/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2956, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
pip._vendor.pkg_resources.RequirementParseError: Expected ',' or end-of-list in uvloop>=0.5.3;platform_system!="Windows" at ;platform_system!="Windows"
```

**Comment by seemethere** [comment]
Do you know what version of setuptools your gitlab-ci is running?

I can understand the issue but I cannot recreate on any of the machines that i have currently.

**Comment by seemethere** [comment]
Also do you have any OS details etc.?

**Comment by gerasim13** [comment]
Hello.
My gitlab-ci is trying to build docker image.
Here is content of my dockerfile (i use alpine as a base image).

```
FROM yellowblackandwhite/alpine-python3
MAINTAINER Pavel Litvinenko <p.litvinenko@start.film>
COPY pip.conf /home/alpine/.pip/pip.conf
ENV PATH=$PATH:/home/alpine/.local/bin
USER root
RUN apk --update add build-base python3-dev py-cryptography libuv-dev linux-headers && \
    pip install cython && \
    pip install --no-binary :all: falcon && \
    apk del linux-headers && \
    rm -rf /root/.cache/pip/* && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*
USER alpine
RUN pip install --user wvproxy
EXPOSE 5000
ENTRYPOINT ["/pip_entry_point.sh"]
CMD ["wvproxy", "-k guv.GuvWorker", "--bind=0.0.0.0:5000", "--workers=9", "--timeout=1200", "--graceful-timeout=90", "--reload", "wvproxy.app:wsgi_app"]
```

Here is build log of yellowblackandwhite/alpine-python3 image:
https://hub.docker.com/r/yellowblackandwhite/alpine-python3/builds/b7tzsfzb8nnqhppubzcrv7t/

**Comment by seemethere** [comment]
Relates to: 1436fb3ef448841dd36991ceb0ccc50ee3d68047

**Comment by seemethere** [comment]
Can you guys try to do a:

```console
pip install git+https://github.com/channelcat/sanic.git
```

If #493 works I'll cut a release for `0.4.1` for today.

**Comment by seemethere** [comment]
@gerasim13, @Sniedes722, and @hyeonjae.

As well as @agoose77 to test if it still works in Windows.

**Comment by Sniedes722** [comment]
@seemethere had success building with 3.5.2

**Comment by subyraman** [comment]
This happens iirc if people are running an outdated version of setuptools. They could fix it with `pip install setuptools --upgrade`

**Comment by gerasim13** [comment]
ok, will try to build with newer version of setuptools.

**Comment by gerasim13** [comment]
Unfortunately i cant install even with setuptools 34.3.0

**Comment by gerasim13** [comment]
This works!
`pip install git+https://github.com/channelcat/sanic.git`

**Comment by seemethere** [comment]
Alright, sanic `0.4.1` was released this morning with a fix for this in particular. Feel free to use `pip install sanic` from here on out.
