### ISSUE TITLE
ecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by bfbd888** [channelcat/sanic#513]
```
Exception ignored in: 'uvloop.loop.Loop._handle_exception'
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 1875, in uvloop.loop.Loop.call_exception_handler (uvloop/loop.c:34943)
  File "/usr/lib/python3.5/logging/__init__.py", line 1309, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1416, in _log
    self.handle(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1426, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1496, in callHandlers
    lastResort.handle(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 856, in handle
    self.emit(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 987, in emit
    self.handleError(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 909, in handleError
    traceback.print_exception(t, v, tb, None, sys.stderr)
  File "/usr/lib/python3.5/traceback.py", line 100, in print_exception
    type(value), value, tb, limit=limit).format(chain=chain):
  File "/usr/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
  File "/usr/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
  File "/usr/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
  File "/usr/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
  File "/usr/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
  File "/usr/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
  File "/usr/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
  File "/usr/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
  File "/usr/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
  File "/usr/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
  File "/usr/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)

```
**Repeat many many times ... ...**

```
  File "/usr/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
  File "/usr/lib/python3.5/traceback.py", line 463, in __init__
    _seen=_seen)
RecursionError: maximum recursion depth exceeded while calling a Python object
/env/sanic/lib/python3.5/site-packages/sanic/server.py:358: RuntimeWarning: coroutine 'on_exception' was never awaited
  loop.run_forever()

```

Ubuntu 16.10
Python 3.5.2
Sanic 0.4.1

Running a web app in docker container for one day.

If restart app and debug it, no error happens.
If keep it alive and wait for a long time, error occurs like that.

My codes is like this:

```
class GlobalErrorHandler(ErrorHandler):
    def default(self, request, exception):
        info = {'ip': request.ip, 'url': request.url, 'exception': str(exception)}
        RuntimeEvent.log_event('error', info)
        return super().default(request, exception)


app = Sanic(__name__, error_handler=GlobalErrorHandler())
 

# log exceptions
@app.exception(NotFound, ServerError, RequestTimeout)
async def on_exception(request: Request, exception: SanicException):
    info = {'ip': request.ip, 'url': request.url, 'exception': str(exception)}
    await zb123.log_event('exception', info)
    return text('error', status=exception.status_code)

app.run(host="0.0.0.0", port=80, workers=4)
```

**Comment by r0fls** [comment]
I cannot reproduce this. I simply get `An error occurred while handling an error` in the browser. Can you try updating to the latest sanic version?

**Comment by r0fls** [comment]
For the record this is what worked for me:

```python
from sanic import Sanic
from sanic.handlers import *
from sanic.exceptions import *
from sanic.request import *

class GlobalErrorHandler(ErrorHandler):
    def default(self, request, exception):
        info = {'ip': request.ip, 'url': request.url, 'exception': str(exception)}
        RuntimeEvent.log_event('error', info)
        return super().default(request, exception)


app = Sanic(__name__, error_handler=GlobalErrorHandler())


# log exceptions
@app.exception(NotFound, ServerError, RequestTimeout)
async def on_exception(request: Request, exception: SanicException):
    info = {'ip': request.ip, 'url': request.url, 'exception': str(exception)}
    await zb123.log_event('exception', info)
    return text('error', status=exception.status_code)

app.run(host="0.0.0.0", port=8000, workers=4)
```

**Comment by bfbd888** [comment]
I have used peewee by peewee_async and start two default eventloop by peewee_async. I don't sure is that reason.

I will try more to get problem detail.

Thanks a lot.
