### ISSUE TITLE
Tests are failing on a freshly cloned repo from master!

### ISSUE THREAD

**Issue by jkbbwr** [channelcat/sanic#598]
Tests are failing on forking and cloning master, how did this even happen?

I am at 3e279cd6704ee20a8ac68b46873d9a113ab2bc31

```
tests/test_bad_request.py .
tests/test_blueprints.py ...........
tests/test_config.py .......
tests/test_cookies.py ......
tests/test_create_task.py .
tests/test_custom_protocol.py .
tests/test_dynamic_routes.py .....
tests/test_exceptions.py ........
tests/test_exceptions_handler.py ......
tests/test_logging.py .
tests/test_middleware.py .....
tests/test_multiprocessing.py .
tests/test_payload_too_large.py ..F
tests/test_redirect.py .....
tests/test_request_data.py ..
tests/test_request_timeout.py FF
tests/test_requests.py ...................
tests/test_response.py ............
tests/test_routes.py ...................................
tests/test_server_events.py .....
tests/test_signal_handlers.py ..
tests/test_static.py .....................
tests/test_url_building.py ..............
tests/test_utf8.py ...
tests/test_vhosts.py ...
tests/test_views.py ...............................

===================================================================================================== FAILURES =====================================================================================================
___________________________________________________________________________________ test_payload_too_large_at_on_header_default ____________________________________________________________________________________

    def test_payload_too_large_at_on_header_default():
        data = 'a' * 1000
        response = on_header_default_app.test_client.post(
>           '/1', gather_request=False, data=data)

tests/test_payload_too_large.py:49: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
sanic/testing.py:81: in post
    return self._sanic_endpoint_test('post', *args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <sanic.testing.SanicTestClient object at 0x7f61a0020c50>, method = 'post', uri = '/1', gather_request = False, debug = False, server_kwargs = {}, request_args = ()
request_kwargs = {'data': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'}
_collect_response = <function SanicTestClient._sanic_endpoint_test.<locals>._collect_response at 0x7f61a001d8c8>

    def _sanic_endpoint_test(
            self, method='get', uri='/', gather_request=True,
            debug=False, server_kwargs={},
            *request_args, **request_kwargs):
        results = [None, None]
        exceptions = []
    
        if gather_request:
            def _collect_request(request):
                if results[0] is None:
                    results[0] = request
            self.app.request_middleware.appendleft(_collect_request)
    
        @self.app.listener('after_server_start')
        async def _collect_response(sanic, loop):
            try:
                response = await self._local_request(
                    method, uri, *request_args,
                    **request_kwargs)
                results[-1] = response
            except Exception as e:
                exceptions.append(e)
            self.app.stop()
    
        self.app.run(host=HOST, debug=debug, port=PORT, **server_kwargs)
        self.app.listeners['after_server_start'].pop()
    
        if exceptions:
>           raise ValueError("Exception during request: {}".format(exceptions))
E           ValueError: Exception during request: [ClientResponseError("400, message='400, message='data received after completed connection: close message''",)]

sanic/testing.py:60: ValueError
----------------------------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------------------------
2017-03-27 08:50:25,421: DEBUG: 
                 ▄▄▄▄▄
        ▀▀▀██████▄▄▄       _______________
      ▄▄▄▄▄  █████████▄  /                 \
     ▀▀▀▀█████▌ ▀▐▄ ▀▐█ |   Gotta go fast!  |
   ▀▀█████▄▄ ▀██████▄██ | _________________/
   ▀▄▄▄▄▄  ▀▀█▄▀█════█▀ |/
        ▀▀▀▄  ▀▀███ ▀       ▄▄
     ▄███▀▀██▄████████▄ ▄▀▀▀▀▀▀█▌
   ██▀▄▄▄██▀▄███▀ ▀▀████      ▄██
▄▀▀▀▄██▄▀▀▌████▒▒▒▒▒▒███     ▌▄▄▀
▌    ▐▀████▐███▒▒▒▒▒▐██▌
▀▄▄▄▄▀   ▀▀████▒▒▒▒▄██▀
          ▀▀█████████▀
        ▄▄██▀██████▀█
      ▄██▀     ▀▀▀  █
     ▄█             ▐▌
 ▄▄▄▄█▌              ▀█▄▄▄▄▀▀▄
▌     ▐                ▀▀▄▄▄▀
 ▀▀▄▄▀

2017-03-27 08:50:25,421: INFO: Goin' Fast @ http://127.0.0.1:42101
2017-03-27 08:50:25,425: INFO: http://127.0.0.1:42101/1
2017-03-27 08:50:25,426: ERROR: NoneType: None

2017-03-27 08:50:25,426: ERROR: NoneType: None

2017-03-27 08:50:25,427: ERROR: Traceback (most recent call last):
  File "/home/jakob/projects/personal/sanic/sanic/app.py", line 464, in handle_request
    handler, args, kwargs = self.router.get(request)
  File "/home/jakob/projects/personal/sanic/sanic/router.py", line 288, in get
    return self._get(request.path, request.method, '')
  File "/home/jakob/projects/personal/sanic/sanic/router.py", line 314, in _get
    raise method_not_supported
sanic.exceptions.InvalidUsage: Method POST not allowed for URL /1

2017-03-27 08:50:25,427: INFO: Starting worker [11544]
2017-03-27 08:50:25,427: INFO: Stopping worker [11544]
2017-03-27 08:50:25,427: INFO: Server Stopped
________________________________________________________________________________________ test_server_error_request_timeout _________________________________________________________________________________________

    def test_server_error_request_timeout():
>       request, response = request_timeout_app.test_client.get('/1')

tests/test_request_timeout.py:24: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
sanic/testing.py:78: in get
    return self._sanic_endpoint_test('get', *args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <sanic.testing.SanicTestClient object at 0x7f61a01ba668>, method = 'get', uri = '/1', gather_request = True, debug = False, server_kwargs = {}, request_args = (), request_kwargs = {}
_collect_request = <function SanicTestClient._sanic_endpoint_test.<locals>._collect_request at 0x7f61a012abf8>
_collect_response = <function SanicTestClient._sanic_endpoint_test.<locals>._collect_response at 0x7f61a001dd90>

    def _sanic_endpoint_test(
            self, method='get', uri='/', gather_request=True,
            debug=False, server_kwargs={},
            *request_args, **request_kwargs):
        results = [None, None]
        exceptions = []
    
        if gather_request:
            def _collect_request(request):
                if results[0] is None:
                    results[0] = request
            self.app.request_middleware.appendleft(_collect_request)
    
        @self.app.listener('after_server_start')
        async def _collect_response(sanic, loop):
            try:
                response = await self._local_request(
                    method, uri, *request_args,
                    **request_kwargs)
                results[-1] = response
            except Exception as e:
                exceptions.append(e)
            self.app.stop()
    
        self.app.run(host=HOST, debug=debug, port=PORT, **server_kwargs)
        self.app.listeners['after_server_start'].pop()
    
        if exceptions:
>           raise ValueError("Exception during request: {}".format(exceptions))
E           ValueError: Exception during request: [ClientResponseError("400, message='400, message='data received after completed connection: close message''",)]

sanic/testing.py:60: ValueError
----------------------------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------------------------
2017-03-27 08:50:25,466: DEBUG: 
                 ▄▄▄▄▄
        ▀▀▀██████▄▄▄       _______________
      ▄▄▄▄▄  █████████▄  /                 \
     ▀▀▀▀█████▌ ▀▐▄ ▀▐█ |   Gotta go fast!  |
   ▀▀█████▄▄ ▀██████▄██ | _________________/
   ▀▄▄▄▄▄  ▀▀█▄▀█════█▀ |/
        ▀▀▀▄  ▀▀███ ▀       ▄▄
     ▄███▀▀██▄████████▄ ▄▀▀▀▀▀▀█▌
   ██▀▄▄▄██▀▄███▀ ▀▀████      ▄██
▄▀▀▀▄██▄▀▀▌████▒▒▒▒▒▒███     ▌▄▄▀
▌    ▐▀████▐███▒▒▒▒▒▐██▌
▀▄▄▄▄▀   ▀▀████▒▒▒▒▄██▀
          ▀▀█████████▀
        ▄▄██▀██████▀█
      ▄██▀     ▀▀▀  █
     ▄█             ▐▌
 ▄▄▄▄█▌              ▀█▄▄▄▄▀▀▄
▌     ▐                ▀▀▄▄▄▀
 ▀▀▄▄▀

2017-03-27 08:50:25,466: INFO: Goin' Fast @ http://127.0.0.1:42101
2017-03-27 08:50:25,467: INFO: http://127.0.0.1:42101/1
2017-03-27 08:50:26,469: ERROR: Traceback (most recent call last):
  File "/home/jakob/projects/personal/sanic/sanic/app.py", line 473, in handle_request
    response = await response
  File "/home/jakob/projects/personal/sanic/tests/test_request_timeout.py", line 14, in handler_1
    await asyncio.sleep(2)
  File "/usr/lib64/python3.6/asyncio/tasks.py", line 476, in sleep
    return (yield from future)
concurrent.futures._base.CancelledError

2017-03-27 08:50:26,469: INFO: Starting worker [11544]
2017-03-27 08:50:26,469: INFO: Stopping worker [11544]
2017-03-27 08:50:26,470: INFO: Server Stopped
____________________________________________________________________________________ test_default_server_error_request_timeout _____________________________________________________________________________________

    def test_default_server_error_request_timeout():
>       request, response = request_timeout_default_app.test_client.get('/1')

tests/test_request_timeout.py:36: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
sanic/testing.py:78: in get
    return self._sanic_endpoint_test('get', *args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <sanic.testing.SanicTestClient object at 0x7f61a0030b38>, method = 'get', uri = '/1', gather_request = True, debug = False, server_kwargs = {}, request_args = (), request_kwargs = {}
_collect_request = <function SanicTestClient._sanic_endpoint_test.<locals>._collect_request at 0x7f61a0117bf8>
_collect_response = <function SanicTestClient._sanic_endpoint_test.<locals>._collect_response at 0x7f61a001de18>

    def _sanic_endpoint_test(
            self, method='get', uri='/', gather_request=True,
            debug=False, server_kwargs={},
            *request_args, **request_kwargs):
        results = [None, None]
        exceptions = []
    
        if gather_request:
            def _collect_request(request):
                if results[0] is None:
                    results[0] = request
            self.app.request_middleware.appendleft(_collect_request)
    
        @self.app.listener('after_server_start')
        async def _collect_response(sanic, loop):
            try:
                response = await self._local_request(
                    method, uri, *request_args,
                    **request_kwargs)
                results[-1] = response
            except Exception as e:
                exceptions.append(e)
            self.app.stop()
    
        self.app.run(host=HOST, debug=debug, port=PORT, **server_kwargs)
        self.app.listeners['after_server_start'].pop()
    
        if exceptions:
>           raise ValueError("Exception during request: {}".format(exceptions))
E           ValueError: Exception during request: [ClientResponseError("400, message='400, message='data received after completed connection: close message''",)]

sanic/testing.py:60: ValueError
----------------------------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------------------------
2017-03-27 08:50:26,480: DEBUG: 
                 ▄▄▄▄▄
        ▀▀▀██████▄▄▄       _______________
      ▄▄▄▄▄  █████████▄  /                 \
     ▀▀▀▀█████▌ ▀▐▄ ▀▐█ |   Gotta go fast!  |
   ▀▀█████▄▄ ▀██████▄██ | _________________/
   ▀▄▄▄▄▄  ▀▀█▄▀█════█▀ |/
        ▀▀▀▄  ▀▀███ ▀       ▄▄
     ▄███▀▀██▄████████▄ ▄▀▀▀▀▀▀█▌
   ██▀▄▄▄██▀▄███▀ ▀▀████      ▄██
▄▀▀▀▄██▄▀▀▌████▒▒▒▒▒▒███     ▌▄▄▀
▌    ▐▀████▐███▒▒▒▒▒▐██▌
▀▄▄▄▄▀   ▀▀████▒▒▒▒▄██▀
          ▀▀█████████▀
        ▄▄██▀██████▀█
      ▄██▀     ▀▀▀  █
     ▄█             ▐▌
 ▄▄▄▄█▌              ▀█▄▄▄▄▀▀▄
▌     ▐                ▀▀▄▄▄▀
 ▀▀▄▄▀

2017-03-27 08:50:26,480: INFO: Goin' Fast @ http://127.0.0.1:42101
2017-03-27 08:50:26,480: INFO: http://127.0.0.1:42101/1
2017-03-27 08:50:27,481: ERROR: NoneType: None

2017-03-27 08:50:27,481: ERROR: Traceback (most recent call last):
  File "/home/jakob/projects/personal/sanic/sanic/app.py", line 473, in handle_request
    response = await response
  File "/home/jakob/projects/personal/sanic/tests/test_request_timeout.py", line 31, in handler_2
    await asyncio.sleep(2)
  File "/usr/lib64/python3.6/asyncio/tasks.py", line 476, in sleep
    return (yield from future)
concurrent.futures._base.CancelledError

2017-03-27 08:50:27,482: INFO: Starting worker [11544]
2017-03-27 08:50:27,482: INFO: Stopping worker [11544]
2017-03-27 08:50:27,482: INFO: Server Stopped
======================================================================================= 3 failed, 207 passed in 9.63 seconds =======================================================================================
```

**Comment by jkbbwr** [comment]
Seems to stem from #431

**Comment by r0fls** [comment]
@jkbbwr this happened because aiohttp changed versions. @seemethere doesn't want to lock in versions but I think we're going to have to, or skip these tests for now, unless someone can solve the mystery. I opened an issue here: https://github.com/aio-libs/aiohttp/issues/1754

If we can provide them more information maybe they will reopen it. I haven't had time to look into this very much. I'm strongly in favor of using locked versions and upgrading them specifically though, to control breakage.

**Comment by jkbbwr** [comment]
Lets do that then. Im going to mark these tests as xskipped until otherwise.

**Comment by r0fls** [comment]
tests are passing again, closing this for now
