### ISSUE TITLE
python -m sanic is broken

### ISSUE THREAD

**Issue by MarSoft** [channelcat/sanic#620]
When I try to start my app using `python -m sanic module.app` I get an error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/repo/env/lib/python3.6/site-packages/sanic/__main__.py", line 34, in <module>
    cert=args.cert, key=args.key)
TypeError: run() got an unexpected keyword argument 'cert'
```
Looks like the code in `__main__.py` went out of sync with actual `Sanic.run` interface. The former one passes `cert` and `key` arguments, while the latter one expects single `ssl` argument.
I am not sure which is the best way to fix this.

**Comment by r0fls** [comment]
Thank you
