### ISSUE TITLE
Unable to start with multiple workers.

### ISSUE THREAD

**Issue by eseglem** [channelcat/sanic#67]
Using https://github.com/channelcat/sanic/blob/master/examples/simple_server.py adding `workers=4` to   run fails. But works fine otherwise:

```
2016-10-18 17:33:20,078: INFO: Goin' Fast @ http://0.0.0.0:8000
2016-10-18 17:33:20,078: INFO: Spinning up 4 workers...
2016-10-18 17:33:20,115: ERROR: Unable to start server: [Errno 22] Invalid argument
2016-10-18 17:33:20,126: ERROR: Unable to start server: [Errno 22] Invalid argument
2016-10-18 17:33:20,140: ERROR: Unable to start server: [Errno 22] Invalid argument
2016-10-18 17:33:20,150: ERROR: Unable to start server: [Errno 22] Invalid argument
```

Will try and debug more in a bit, but not sure what is going on yet.

Oh, and running the latest version from pip, have not pulled the latest git, if there has been a fix already.

**Comment by channelcat** [comment]
Hmm, I'm unable to reproduce on 0.1.4 :(.  I've updated the master branch to print out the exception, if you're able to run against the latest master.

**Comment by eseglem** [comment]
Very odd...
```
2016-10-18 21:48:36,106: ERROR: Unable to start server
Traceback (most recent call last):
  File "/mnt/c/workspace/webtest/venv/lib/python3.5/site-packages/Sanic-0.1.4-py3.5.egg/sanic/server.py", line 181, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1120, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:20258)
  File "uvloop/future.pyx", line 146, in uvloop.loop.BaseFuture.result (uvloop/loop.c:93560)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:93099)
  File "uvloop/task.pyx", line 126, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:98843)
  File "uvloop/loop.pyx", line 1271, in create_server (uvloop/loop.c:21971)
  File "uvloop/loop.pyx", line 796, in uvloop.loop.Loop._create_server (uvloop/loop.c:17187)
  File "uvloop/loop.pyx", line 753, in uvloop.loop.Loop._sock_set_reuseport (uvloop/loop.c:16672)
```

**Comment by santagada** [comment]
I don't think windows support reusing ports. Take a look on the multiprocessing docs: https://docs.python.org/3.6/library/multiprocessing.html#contexts-and-start-methods 

I don't fully understand how linux runs on windows, but if it is using windows kernel maybe reuseport doesn't work.

**Comment by channelcat** [comment]
Without being able to reuse ports, I'm not sure Sanic can natively support multiprocessing on Windows.  Unless there's a way to have multiple python processes share a socket on Windows, we might want to ask Microsoft to support it in Ubuntu on Windows (maybe we want to anyways):
https://github.com/Microsoft/BashOnWindows/issues

**Comment by hainm** [comment]
happens on Linux too

```bash
sanic/tests/performance/sanic (master) $ python simple_server.py 8000

2016-10-19 14:53:54,471: INFO: Goin' Fast @ http://0.0.0.0:8000
2016-10-19 14:53:54,471: INFO: Spinning up 4 workers...
2016-10-19 14:53:54,479: ERROR: Unable to start server
Traceback (most recent call last):
  File "/u2/home/haichit/programs/sanic/tests/performance/sanic/../../../sanic/server.py", line 197, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1120, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:20269)
  File "uvloop/future.pyx", line 146, in uvloop.loop.BaseFuture.result (uvloop/loop.c:93571)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:93110)
  File "uvloop/task.pyx", line 126, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:98854)
  File "uvloop/loop.pyx", line 1247, in create_server (uvloop/loop.c:21604)
ValueError: reuse_port not supported by socket module
```

**Comment by channelcat** [comment]
@hainm Hmmm, it should be supported since linux kernel 3.9 (2013).  I'll see if I can set Sanic up to share a socket instead of reusing ports when the option is not available.

**Comment by hainm** [comment]
@channelcat uhm, I see. I am using very old kernel: 2.6.35 :D

**Comment by santagada** [comment]
why are you still using kernel 2.6.35? I do remember something important of old hardware was removed in that version but don't remember what. was it math co-processor emulation?

**Comment by hainm** [comment]
> why are you still using kernel 2.6.35?

because I am not allowed to upgrade it. It's in school.

**Comment by eseglem** [comment]
That sounds like a massive security risk for the school to not upgrade....but anyways, I am guess it has something to do with Windows under the hood for me. I don't completely understand, but from what I understand they basically translate linux kernel commands to windows underneath. And if the Windows kernel can't do it under the hood, might break things. 

I would definitely like to see the ability to share sockets instead of port, even if in my case I had to manually specify it. Can I tell it to use `/tmp/sanic.sock` or something like that?

**Comment by zhyc9de** [comment]
i run 2 workers in debian 7, and i upgrade kernel to 3.16, but the error still happened
```
2016-12-24 13:48:15,141: INFO: Goin' Fast @ http://0.0.0.0:8800
2016-12-24 13:48:15,141: INFO: Spinning up 2 workers...
2016-12-24 13:48:15,175: ERROR: Unable to start server
Traceback (most recent call last):
  File "/usr/local/python35/lib/python3.5/site-packages/sanic/server.py", line 262, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1186, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:23880)
  File "uvloop/future.pyx", line 146, in uvloop.loop.BaseFuture.result (uvloop/loop.c:102824)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:102363)
  File "uvloop/future.pyx", line 372, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:105885)
  File "uvloop/loop.pyx", line 1322, in create_server (uvloop/loop.c:25356)
ValueError: reuse_port not supported by socket module2016-12-24 13:48:15,174: ERROR: Unable to start server
Traceback (most recent call last):
  File "/usr/local/python35/lib/python3.5/site-packages/sanic/server.py", line 262, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1186, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:23880)
  File "uvloop/future.pyx", line 146, in uvloop.loop.BaseFuture.result (uvloop/loop.c:102824)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:102363)
  File "uvloop/future.pyx", line 372, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:105885)
  File "uvloop/loop.pyx", line 1322, in create_server (uvloop/loop.c:25356)
ValueError: reuse_port not supported by socket module
```

**Comment by seanpar203** [comment]
I ran into this issue when I was manually trying to create a uvloop policy and pass it into the loop argument on `Sanic.run`.

**Comment by r0fls** [comment]
Does this issue still exist on the current master branch? It may have been fixed with this PR:
https://github.com/channelcat/sanic/pull/276

**Comment by seemethere** [comment]
No it should not. Closing per #267
