### ISSUE TITLE
Why the sanic websocket close from the client got an error?

### ISSUE THREAD

**Issue by ihjmh** [channelcat/sanic#708]
After clinet close the websocket ,I got errors like this:
```
[ERROR]: Exception occured in one of response middleware handlers
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic-0.5.4-py3.5.egg/sanic/app.py", line 495, in handle_request
    response)
  File "/usr/local/lib/python3.5/dist-packages/sanic-0.5.4-py3.5.egg/sanic/app.py", line 621, in _run_response_middleware
    _response = await _response
  File "/home/oeasy/.local/lib/python3.5/site-packages/sanic_cors/extension.py", line 237, in cors_response_middleware
    elif resp.headers.get(ACL_ORIGIN):
AttributeError: 'NoneType' object has no attribute 'headers'
```
In fact,I wanna a normal notification that I can use, the source codes are from the sanic example
Anyone can help me?Thanks very much !

**Comment by seemethere** [comment]
Looks like an issue with the the `sanic_cors` package not necessarily core `sanic`

**Comment by qwexvf** [comment]
Already reported but.....
https://github.com/ashleysommer/sanic-cors/issues/2

sad .,

**Comment by seemethere** [comment]
Looks like it got cleared up on the extension side, closing for now. Will re-open if necessary.
