### ISSUE TITLE
Errors when running py.test on tests folder

### ISSUE THREAD

**Issue by stopspazzing** [channelcat/sanic#767]
`python 3.6.1`

`test_payload_too_large.py`
`test_payload_too_large_at_on_header_default()`
```
2017-06-02 09:45:05 - (sanic)[ERROR]: Exception:
Traceback (most recent call last):
  File "/home/test/sanic/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 552, in start
    (message, payload) = yield from self._protocol.read()
  File "/home/test/sanic/lib/python3.6/site-packages/aiohttp/streams.py", line 509, in read
    yield from self._waiter
  File "/home/test/sanic/lib/python3.6/site-packages/aiohttp/client_proto.py", line 165, in data_received
    messages, upgraded, tail = self._parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 273, in aiohttp._http_parser.HttpParser.feed_data (aiohttp/_http_parser.c:4351)
aiohttp.http_exceptions.BadHttpMessage: 400, message='data received after completed connection: close message'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/test/PycharmProjects/sanic/sanic/testing.py", line 52, in _collect_response
    **request_kwargs)
  File "/home/test/PycharmProjects/sanic/sanic/testing.py", line 26, in _local_request
    session, method.lower())(url, *args, **kwargs) as response:
  File "/home/test/sanic/lib/python3.6/site-packages/aiohttp/client.py", line 636, in __aenter__
    self._resp = yield from self._coro
  File "/home/test/sanic/lib/python3.6/site-packages/aiohttp/client.py", line 240, in _request
    yield from resp.start(conn, read_until_eof)
  File "/home/test/sanic/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 557, in start
    message=exc.message, headers=exc.headers) from exc
aiohttp.client_exceptions.ClientResponseError: 400, message='data received after completed connection: close message'

2017-06-02 09:45:05 - (sanic)[INFO]: Starting worker [6184]
2017-06-02 09:45:05 - (sanic)[INFO]: Stopping worker [6184]
2017-06-02 09:45:05 - (sanic)[INFO]: Server Stopped

tests/test_payload_too_large.py:36 (test_payload_too_large_at_on_header_default)
def test_payload_too_large_at_on_header_default():
        on_header_default_app = Sanic('on_header')
        on_header_default_app.config.REQUEST_MAX_SIZE = 500
    
        @on_header_default_app.post('/1')
        async def handler3(request):
            return text('OK')
    
        data = 'a' * 1000
        response = on_header_default_app.test_client.post(
>           '/1', gather_request=False, data=data)

test_payload_too_large.py:47: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../sanic/testing.py:85: in post
    return self._sanic_endpoint_test('post', *args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <sanic.testing.SanicTestClient object at 0x7eff66c452e8>, method = 'post'
uri = '/1', gather_request = False, debug = False, server_kwargs = {}
request_args = ()
request_kwargs = {'data': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'}
_collect_response = <function SanicTestClient._sanic_endpoint_test.<locals>._collect_response at 0x7eff5dbbf048>

    def _sanic_endpoint_test(
            self, method='get', uri='/', gather_request=True,
            debug=False, server_kwargs={},
            *request_args, **request_kwargs):
        results = [None, None]
        exceptions = []
    
        if gather_request:
            def _collect_request(request):
                if results[0] is None:
                    results[0] = request
            self.app.request_middleware.appendleft(_collect_request)
    
        @self.app.listener('after_server_start')
        async def _collect_response(sanic, loop):
            try:
                response = await self._local_request(
                    method, uri, *request_args,
                    **request_kwargs)
                results[-1] = response
            except Exception as e:
                log.error(
                    'Exception:\n{}'.format(traceback.format_exc()))
                exceptions.append(e)
            self.app.stop()
    
        self.app.run(host=HOST, debug=debug, port=PORT, **server_kwargs)
        self.app.listeners['after_server_start'].pop()
    
        if exceptions:
>           raise ValueError("Exception during request: {}".format(exceptions))
E           ValueError: Exception during request: [ClientResponseError("400, message='data received after completed connection: close message'",)]

../sanic/testing.py:64: ValueError
```

----
`test_request_timeout.py`
`test_server_error_request_timeout()`
```
2017-06-02 09:45:06 - (sanic)[ERROR]: Traceback (most recent call last):
  File "/home/test/PycharmProjects/sanic/sanic/app.py", line 495, in handle_request
    response = await response
  File "/home/test/PycharmProjects/sanic/tests/test_request_timeout.py", line 14, in handler_1
    await asyncio.sleep(2)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 476, in sleep
    return (yield from future)
concurrent.futures._base.CancelledError

2017-06-02 09:45:06 - (network)[INFO][127.0.0.1:44896]: GET http://127.0.0.1:42101/1  500 144
2017-06-02 09:45:06 - (sanic)[ERROR]: Exception:
Traceback (most recent call last):
  File "/home/test/sanic/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 552, in start
    (message, payload) = yield from self._protocol.read()
  File "/home/test/sanic/lib/python3.6/site-packages/aiohttp/streams.py", line 509, in read
    yield from self._waiter
  File "/home/test/sanic/lib/python3.6/site-packages/aiohttp/client_proto.py", line 165, in data_received
    messages, upgraded, tail = self._parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 273, in aiohttp._http_parser.HttpParser.feed_data (aiohttp/_http_parser.c:4351)
aiohttp.http_exceptions.BadHttpMessage: 400, message='data received after completed connection: close message'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/test/PycharmProjects/sanic/sanic/testing.py", line 52, in _collect_response
    **request_kwargs)
  File "/home/test/PycharmProjects/sanic/sanic/testing.py", line 26, in _local_request
    session, method.lower())(url, *args, **kwargs) as response:
  File "/home/test/sanic/lib/python3.6/site-packages/aiohttp/client.py", line 636, in __aenter__
    self._resp = yield from self._coro
  File "/home/test/sanic/lib/python3.6/site-packages/aiohttp/client.py", line 240, in _request
    yield from resp.start(conn, read_until_eof)
  File "/home/test/sanic/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 557, in start
    message=exc.message, headers=exc.headers) from exc
aiohttp.client_exceptions.ClientResponseError: 400, message='data received after completed connection: close message'

2017-06-02 09:45:06 - (sanic)[INFO]: Starting worker [6184]
2017-06-02 09:45:06 - (sanic)[INFO]: Stopping worker [6184]
2017-06-02 09:45:06 - (sanic)[INFO]: Server Stopped

tests/test_request_timeout.py:22 (test_server_error_request_timeout)
def test_server_error_request_timeout():
>       request, response = request_timeout_app.test_client.get('/1')

test_request_timeout.py:24: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../sanic/testing.py:82: in get
    return self._sanic_endpoint_test('get', *args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <sanic.testing.SanicTestClient object at 0x7eff5db35cc0>, method = 'get'
uri = '/1', gather_request = True, debug = False, server_kwargs = {}
request_args = (), request_kwargs = {}
_collect_request = <function SanicTestClient._sanic_endpoint_test.<locals>._collect_request at 0x7eff5db288c8>
_collect_response = <function SanicTestClient._sanic_endpoint_test.<locals>._collect_response at 0x7eff5db28730>

    def _sanic_endpoint_test(
            self, method='get', uri='/', gather_request=True,
            debug=False, server_kwargs={},
            *request_args, **request_kwargs):
        results = [None, None]
        exceptions = []
    
        if gather_request:
            def _collect_request(request):
                if results[0] is None:
                    results[0] = request
            self.app.request_middleware.appendleft(_collect_request)
    
        @self.app.listener('after_server_start')
        async def _collect_response(sanic, loop):
            try:
                response = await self._local_request(
                    method, uri, *request_args,
                    **request_kwargs)
                results[-1] = response
            except Exception as e:
                log.error(
                    'Exception:\n{}'.format(traceback.format_exc()))
                exceptions.append(e)
            self.app.stop()
    
        self.app.run(host=HOST, debug=debug, port=PORT, **server_kwargs)
        self.app.listeners['after_server_start'].pop()
    
        if exceptions:
>           raise ValueError("Exception during request: {}".format(exceptions))
E           ValueError: Exception during request: [ClientResponseError("400, message='data received after completed connection: close message'",)]

../sanic/testing.py:64: ValueError
```

`test_default_server_error_request_timeout()`
```
2017-06-02 09:45:07 - (sanic)[ERROR]: Traceback (most recent call last):
  File "/home/test/PycharmProjects/sanic/sanic/app.py", line 495, in handle_request
    response = await response
  File "/home/test/PycharmProjects/sanic/tests/test_request_timeout.py", line 31, in handler_2
    await asyncio.sleep(2)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 476, in sleep
    return (yield from future)
concurrent.futures._base.CancelledError

2017-06-02 09:45:07 - (network)[INFO][127.0.0.1:44897]: GET http://127.0.0.1:42101/1  500 144
2017-06-02 09:45:07 - (sanic)[ERROR]: Exception:
Traceback (most recent call last):
  File "/home/test/sanic/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 552, in start
    (message, payload) = yield from self._protocol.read()
  File "/home/test/sanic/lib/python3.6/site-packages/aiohttp/streams.py", line 509, in read
    yield from self._waiter
  File "/home/test/sanic/lib/python3.6/site-packages/aiohttp/client_proto.py", line 165, in data_received
    messages, upgraded, tail = self._parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 273, in aiohttp._http_parser.HttpParser.feed_data (aiohttp/_http_parser.c:4351)
aiohttp.http_exceptions.BadHttpMessage: 400, message='data received after completed connection: close message'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/test/PycharmProjects/sanic/sanic/testing.py", line 52, in _collect_response
    **request_kwargs)
  File "/home/test/PycharmProjects/sanic/sanic/testing.py", line 26, in _local_request
    session, method.lower())(url, *args, **kwargs) as response:
  File "/home/test/sanic/lib/python3.6/site-packages/aiohttp/client.py", line 636, in __aenter__
    self._resp = yield from self._coro
  File "/home/test/sanic/lib/python3.6/site-packages/aiohttp/client.py", line 240, in _request
    yield from resp.start(conn, read_until_eof)
  File "/home/test/sanic/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 557, in start
    message=exc.message, headers=exc.headers) from exc
aiohttp.client_exceptions.ClientResponseError: 400, message='data received after completed connection: close message'

2017-06-02 09:45:07 - (sanic)[INFO]: Starting worker [6184]
2017-06-02 09:45:07 - (sanic)[INFO]: Stopping worker [6184]
2017-06-02 09:45:07 - (sanic)[INFO]: Server Stopped

tests/test_request_timeout.py:34 (test_default_server_error_request_timeout)
def test_default_server_error_request_timeout():
>       request, response = request_timeout_default_app.test_client.get('/1')

test_request_timeout.py:36: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../sanic/testing.py:82: in get
    return self._sanic_endpoint_test('get', *args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <sanic.testing.SanicTestClient object at 0x7eff5db26438>, method = 'get'
uri = '/1', gather_request = True, debug = False, server_kwargs = {}
request_args = (), request_kwargs = {}
_collect_request = <function SanicTestClient._sanic_endpoint_test.<locals>._collect_request at 0x7eff5db8ec80>
_collect_response = <function SanicTestClient._sanic_endpoint_test.<locals>._collect_response at 0x7eff5db8e9d8>

    def _sanic_endpoint_test(
            self, method='get', uri='/', gather_request=True,
            debug=False, server_kwargs={},
            *request_args, **request_kwargs):
        results = [None, None]
        exceptions = []
    
        if gather_request:
            def _collect_request(request):
                if results[0] is None:
                    results[0] = request
            self.app.request_middleware.appendleft(_collect_request)
    
        @self.app.listener('after_server_start')
        async def _collect_response(sanic, loop):
            try:
                response = await self._local_request(
                    method, uri, *request_args,
                    **request_kwargs)
                results[-1] = response
            except Exception as e:
                log.error(
                    'Exception:\n{}'.format(traceback.format_exc()))
                exceptions.append(e)
            self.app.stop()
    
        self.app.run(host=HOST, debug=debug, port=PORT, **server_kwargs)
        self.app.listeners['after_server_start'].pop()
    
        if exceptions:
>           raise ValueError("Exception during request: {}".format(exceptions))
E           ValueError: Exception during request: [ClientResponseError("400, message='data received after completed connection: close message'",)]

../sanic/testing.py:64: ValueError
```

**Comment by seemethere** [comment]
Can you post your results when you try to run `make test` in the base directory?

Also can you post your `pip freeze` results as well?

**Comment by stopspazzing** [comment]
first error seems issue with docker not being installed. Working on fixing that, second:
```
test@ae5n6wb46vq35 ~ $ python3.6 -V
Python 3.6.1
test@ae5n6wb46vq35 ~ $ python3.6 -m pip freeze
test@ae5n6wb46vq35 ~ $
test@ae5n6wb46vq35 ~ $ python3.6 -m pip --version
pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)

```

**Comment by seemethere** [comment]
you don't have any packages installed?

**Comment by stopspazzing** [comment]
Oops sorry, I used a venv and not use to activating it on in terminal.
```
(sanic) test@ae5n6wb46vq35 ~ $ python3.6 -m pip freeze
aiocache==0.5.2
aiofiles==0.3.1
aiohttp==2.1.0
aiomcache==0.5.2
aioodbc==0.1.0
aioredis==0.3.1
appdirs==1.4.3
async-timeout==1.2.1
asyncorm==0.0.10
beautifulsoup4==4.6.0
certifi==2017.4.17
chardet==3.0.3
CommonMark==0.7.3
docutils==0.13.1
future==0.16.0
gunicorn==19.7.1
hiredis==0.2.0
httptools==0.0.9
idna==2.5
Jinja2==2.9.6
MarkupSafe==1.0
multidict==2.1.6
packaging==16.8
py==1.4.33
pyodbc==4.0.16
pyparsing==2.2.0
pytest==3.1.1
recommonmark==0.4.0
requests==2.17.3
sanic==0.5.4
Sanic-Auth==0.1.0
sanic-compress==0.1.1
sanic-jinja2==0.5.3
sanic-session==0.1.3
sanic-useragent==0.1.2
Sanic-WTF==0.5.0
six==1.10.0
ujson==1.35
urllib3==1.21.1
uvloop==0.8.0
websockets==3.3
WTForms==2.1
yarl==0.10.2
```

**Comment by seemethere** [comment]
`aiohttp==2.1.0` <- That's why your tests are failing

These are our dev requirements:

<img width="167" alt="screen shot 2017-06-02 at 11 40 19 am" src="https://cloud.githubusercontent.com/assets/1700823/26739860/4fc6aa36-4788-11e7-9de7-4d78d4544d75.png">

**Comment by stopspazzing** [comment]
Ah, so user error. Upgrading to Aiohttp 2.1.0 anytime soon? https://pypi.python.org/pypi/aiohttp
adds speed increases...

> Finally uvloop gives performance improvement. Overall performance improvement should be around 70-90% compared to 1.x version.

http://aiohttp.readthedocs.io/en/latest/migration.html

**Comment by seemethere** [comment]
Well, we might, depends on if we can fix the tests that go along with it.
