### ISSUE TITLE
Why not add the sanic.worker.GunicornWorker to  Gunicorn default worker_class

### ISSUE THREAD

**Issue by kolapapa** [channelcat/sanic#956]
In my project, what im using is gunicorn and oslo.config , and before i use flask + gunicorn + oslo.config,  `gunicorn.app.base.BaseApplication`  This can be written into my code,  Why don't you add it to the default?

I tried it:
```python
from sanic.worker import GunicronWorker
class StandaloneApplication(gunicorn.app.base.BaseApplication):

    def __init__(self, app, options=None):
        self.options = {
           'workers': 2,
           'worker_class': GunicronWorker
        }
        self.application = app
        super(StandaloneApplication, self).__init__()
     ...
`
But there's a problem with it.


Traceback (most recent call last):
  File "gunicron_app.py", line 88, in <module>
    StandaloneApplication(app, options).run()
  File "/Users/liukai/workspace/test/sanic_pro/sanic_gunicorn/.venv/lib/python3.5/site-packages/gunicorn/app/base.py", line 203, in run
    super(Application, self).run()
  File "/Users/liukai/workspace/test/sanic_pro/sanic_gunicorn/.venv/lib/python3.5/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/Users/liukai/workspace/test/sanic_pro/sanic_gunicorn/.venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 198, in run
    self.start()
  File "/Users/liukai/workspace/test/sanic_pro/sanic_gunicorn/.venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 162, in start
    self.log.info("Using worker: %s", self.cfg.worker_class_str)
  File "/Users/liukai/workspace/test/sanic_pro/sanic_gunicorn/.venv/lib/python3.5/site-packages/gunicorn/config.py", line 68, in __getattr__
    raise AttributeError("No configuration setting for: %s" % name)
AttributeError: No configuration setting for: worker_class_str
```
So I can only change the gunicorn source code.

**Comment by jrocketfingers** [comment]
Moot point probably, but `Gunicron`? Not to mention that it expects `worker_class_str` too, I assume you'd need to expand on the options? Or is that done in the base class init?

**Comment by kolapapa** [comment]
**Thank you for your reply, I also tried to add options, but still did not solve**
```python
class Config(object):

    def __init__(self, usage=None, prog=None):
        self.settings = make_settings()
        self.usage = usage
        self.prog = prog or os.path.basename(sys.argv[0])
        self.env_orig = os.environ.copy()

    def __getattr__(self, name):
        if name not in self.settings:
            raise AttributeError("No configuration setting for: %s" % name)
        return self.settings[name].get()

    def __setattr__(self, name, value):
        if name != "settings" and name in self.settings:
            raise AttributeError("Invalid access!")
        super(Config, self).__setattr__(name, value)
    @property
    def worker_class_str(self):
        uri = self.settings['worker_class'].get()

        ## are we using a threaded worker?
        is_sync = uri.endswith('SyncWorker') or uri == 'sync'
        if is_sync and self.threads > 1:
            return "threads"
        return uri
```
`worker_class_str` is from worker_class 

```python
def worker_class_str(self):
        uri = self.settings['worker_class'].get()
        return str(uri)          # if i write this, it works
        ...
```

**Comment by yunstanford** [comment]
Does it expect `string` instead ? but i didn't try..
Why do you wanna create the `StandaloneApplication` class?

cmd line seems to work fine, or provide a config file `gunicorn_config.py`.
```
gunicorn --bind 127.0.0.1:1337 --worker-class sanic.worker.GunicornWorker examples.simple_server:app
```
Maybe i misunderstand your question..

**Comment by messense** [comment]
The `GunicornWorker` is intented for using with `gunicorn` command line.

**Comment by messense** [comment]
You should avoid changing `gunicorn` source code IMO, just use the command line or a configuration file.

[The `gaiohttp` gunicorn worker will be deprecated soon](https://github.com/benoitc/gunicorn/pull/1569).

**Comment by kolapapa** [comment]
@yunstanford 
Because our automated build tools already have one，its like `tools/with_venv.sh sanic_web --config-file etc/production/sanic_web.conf`  .We use `oslo.config` for unified configuration.These two configurations are not available at the same time.

@messense 
emmm... Should I go there proposes a PR？
