### ISSUE TITLE
How to install libssl.so.10 for sanic? Thank you

### ISSUE THREAD

**Issue by guotong1988** [channelcat/sanic#993]
I'm in ubuntu. Thank you.

**Comment by guotong1988** [comment]
After I follow [this](https://askubuntu.com/questions/339364/libssl-so-10-cannot-open-shared-object-file-no-such-file-or-directory) to install it.
I get error:
```
/nfsdata/guotong_data/Py35/bin/python3 /nfsdata/guotong_data/allennlp-master/allennlp/run.py
Traceback (most recent call last):
  File "/nfsdata/guotong_data/allennlp-master/allennlp/run.py", line 10, in <module>
    from allennlp.commands import main  # pylint: disable=wrong-import-position
  File "/nfsdata/guotong_data/allennlp-master/allennlp/commands/__init__.py", line 4, in <module>
    from allennlp.commands.serve import add_subparser as add_serve_subparser
  File "/nfsdata/guotong_data/allennlp-master/allennlp/commands/serve.py", line 27, in <module>
    from allennlp.service import server_sanic
  File "/nfsdata/guotong_data/allennlp-master/allennlp/service/server_sanic.py", line 16, in <module>
    from sanic import Sanic, response, request
  File "/nfsdata/guotong_data/Py35/lib/python3.5/site-packages/sanic/__init__.py", line 1, in <module>
    from sanic.app import Sanic
  File "/nfsdata/guotong_data/Py35/lib/python3.5/site-packages/sanic/app.py", line 11, in <module>
    from ssl import create_default_context, Purpose
  File "/nfsdata/guotong_data/Py35/lib/python3.5/ssl.py", line 99, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: /lib/x86_64-linux-gnu/libssl.so.10: version `libssl.so.10' not found (required by /nfsdata/guotong_data/Py35/lib/python3.5/lib-dynload/_ssl.cpython-35m-x86_64-linux-gnu.so)

```

**Comment by guotong1988** [comment]
I follow [this](https://stackoverflow.com/questions/23548188/how-do-i-compile-python-3-4-with-custom-openssl) and solve it.
Note that, must use the so file from openssl.tar.gz and don't use the so file from `apt-get install`
Otherwise it will throw the `version` error.
